name: caller

on:
  workflow_call:
  workflow_dispatch:

jobs:
  artifact-generator:
    runs-on: ubuntu-latest
    steps:
    - name: artifact-generate
      run: |
        echo "test" > test.txt
      shell: bash

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: artifact-data

  consume-artifact:
   runs-on: ubuntu-latest
   steps:
    - name: consume
      uses: actions/download-artifact@v5
      with:
        path: artifacts
    - name: display-artifacts
      run: |
        tree
        ls -la artifacts
