name: caller

on:
  push:
    branches:
      - "main"
  workflow_call:
  workflow_dispatch:

jobs:
  call-reusable:
    name: call reusable
    uses: Vininhos/reusable/.github/workflows/reusable.yaml
    secrets: inherit
