name: caller

on:
  workflow_dispatch:

jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-latest
    steps:
    - name: artifact-generate
      run: |
        mkdir -p artifact-data
        echo "test" > artifact-data/test.txt
      shell: bash

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-a
        path: artifact-data

  job-b:
   name: Job B
   needs: job-a
   runs-on: ubuntu-latest
   steps:
    - name: download-artifact
      uses: actions/download-artifact@v5
      with:
        name: artifact-a
        path: artifact-data

    - name: display-artifacts
      run: |
        tree
        ls -la

  job-c:
   name: Job C
   needs: job-a
   runs-on: ubuntu-latest
   steps:
    - name: download-artifact
      uses: actions/download-artifact@v5
      with:
        name: artifact-a
        path: artifact-data

    - name: display-artifacts
      run: |
        tree
        ls -la
