name: caller

on:
  workflow_call:
  workflow_dispatch:

jobs:
  artifact-generator:
    runs-on: ubuntu-latest
    steps:
    - name: artifact-generate
      run: |
        mkdir -p artifact-data
        echo "test" > artifact-data/test.txt
      shell: bash

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: manager-generator
        path: artifact-data

  consume-artifact:
   needs: artifact-generator
   runs-on: ubuntu-latest
   steps:
    - name: consume
      uses: actions/download-artifact@v5
      with:
        pattern: manager-
    - name: display-artifacts
      run: |
        tree
        ls -la
